pub mod owner_scope_test;
mod slice_test;
mod string_test;
mod struct_test;
mod data_test;
mod enumeration_test;
mod vector_test;
mod hashmap_test;
mod err_handle_test;
mod generics_test;
mod trait_test;
mod lifetime_test;
mod bytes_test;